log-level:info
fullscreen:false

camera-transport:auto
camera-url:https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8,https://test-streams.mux.dev/tos_ismc/main.m3u8,https://stream.mux.com/v69RSHhFelSm4701snP22dYz2jICy4E4FUyk02rW4gxRM.m3u8,https://test-streams.mux.dev/pts_shift/master.m3u8,https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8
camera-hold-ms:-1

db-host:127.0.0.1
db-port:55432
db-name:kuchnia_demo
db-user:demo
db-password:demo
db-interval-ms:30000
db-history-hours:24

mqtt-host:127.0.0.1
mqtt-client-id:kuchnia-demo
mqtt-status-topic:kuchnia/available

people-url:http://127.0.0.1:8087/v1/people
people-interval-ms:60000
map-tile-url:https://tile.openstreetmap.org/

rest-url:https://api.open-meteo.com/v1/forecast?latitude=<set-me>&longitude=<set-me>&current=temperature_2m,relative_humidity_2m,weather_code,wind_speed_10m,wind_direction_10m,cloud_cover,rain,snowfall&hourly=temperature_2m,precipitation_probability,precipitation,cloud_cover&daily=sunrise,sunset&forecast_days=8
rest-interval-ms:300000

radio-m3u:demo/radio.m3u
key-bindings:demo/keys.ini
